# Generated by Django 5.2.8 on 2025-12-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'TO DO'), ('in_progress', 'In Progress'), ('done', 'Done'), ('overdue', 'Overdue')], default='todo', max_length=12),
        ),
    ]
